import speech_recognition as sr
import webbrowser
import time
import playsound
import os
import random
from gtts import gTTS

# Initialize a recognizer, this is respoinsible for handling our speech queries
r = sr.Recognizer()
def record_audio(ask=False):
    with sr.Microphone() as source:
        if ask:
            pyri_speech(ask)
        # captured audio from user
        audio = r.listen(source)
        voice_data = ''

        try:
            # user's voice query, processed using google's API
            voice_data = r.recognize_google(audio)
        except sr.UnknownValueError:
            # unable to understand speech query
            pyri_speech("Apologies, but I couldn't understand that.")
        except sr.RequestError:
            # can't connect to Google's servers or having a general networking error
            pyri_speech("I'm terribly sorry, but I'm having problems phoning home right now")
        return voice_data

def respond_to_query(voice_data):
    if 'what is your name' in voice_data:
        pyri_speech("How kind of you to ask! My name is Pyri!")
    if 'what time is it' in voice_data:
        pyri_speech(time.strftime('%H:%M'))
    if 'search' in voice_data:
        # ask for search query
        search = record_audio('What would you like to search for?')
        url = f"https://google.com/search?q={search}"
        webbrowser.get().open(url)
        pyri_speech(f"OK, this is what I found on the topic of {search}.")
    if 'find location' in voice_data:
        location = record_audio("What's the name of the location you need help finding?")
        url = f"https://google.nl/maps/place/{location}/&amp;"
        webbrowser.get().open(url)
        pyri_speech(f"OK, here's where {location} is located on the map.")
    if 'goodbye' in voice_data:
        pyri_speech("Bye! See you soon!")
        exit()

def pyri_speech(audio_string):
    tts = gTTS(text=audio_string, lang="en")
    # create a filename for audio file generated by tts
    r = random.randint(1, 10000000)
    audio_file = "audio-" + str(r) + ".mp3"
    tts.save(audio_file)

    #play the audio using playsound pkg, right away
    playsound.playsound(audio_file)
    print(audio_string) # for testing purposes

    # delete the audio file when done to keep them from stacking up
    os.remove(audio_file)

def init():
    pyri_speech('Hi! What can I do for you?')
    time.sleep(1)

    while 1:
        user_query = record_audio()
        respond_to_query(user_query)

init()